#!/bin/bash

DEST=/usr/local/ssl-tunnel
echo "Copy scripts"
sudo cp ssl-tunnel /etc/init.d/
sudo mkdir -p $DEST
sudo chmod 0755 $DEST
sudo cp ./native/bin/tunnel $DEST/ssl-tunnel
sudo cp ./python/ssl-tunnel.py $DEST/
sudo cp ./ssl-tunnel.sh $DEST/
sudo cp ./pem/server.csr $DEST/

cd $DEST/
sudo chmod 0777 .

#echo "Generate certificate request"
#openssl req -new -nodes -out server.csr

#echo "Generate private key"
#openssl genrsa -out key.pem 2048

#echo "Generate the certifucate"
#openssl x509 -req -days 365 -in server.csr -signkey key.pem -out cert.pem

sudo chown root:root *
sudo chmod 0400 *
sudo chmod 0500 ssl-tunnel
sudo chmod 0500 ssl-tunnel.py
sudo chmod 0500 ssl-tunnel.sh

sudo update-rc.d ssl-tunnel defaults

